# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos9820.dtb
dtbo-y += exynos9820-beyond1lte_kor_17.dtbo
dtbo-y += exynos9820-beyond1lte_kor_18.dtbo
dtbo-y += exynos9820-beyond1lte_kor_19.dtbo
dtbo-y += exynos9820-beyond1lte_kor_20.dtbo
dtbo-y += exynos9820-beyond1lte_kor_21.dtbo
dtbo-y += exynos9820-beyond1lte_kor_26.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
